<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Vendor view template
 *
 * @see \Slavik\Elogic\Block\Product\View\Vendor
 */
?>
<?php
$_vendorName = $block->getVendorName();
$_vendorDescription = $block->getVendorDescription();
?>

<?php echo( "Vendor name: $_vendorName <br> Vendor description: $_vendorDescription")?>
